version: '3.8'

services:
  mock-api:
    build: ./mock-api
    restart: always
    ports:
      - '8000:8000'
    volumes:
       - ./mock-api/test_data:/app/test_data
#    networks:
#      - app-network

#  bot:
#    build: ./bot
#    ports:
#      - "8080:8080"
#    networks:
#      - app-network


#volumes:
#  db_data:

#networks:
#  app-network: